# Generated by Django 4.0.3 on 2022-04-22 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='NEW', max_length=50, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Finished')),
            ],
        ),
        migrations.CreateModel(
            name='AbsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_task_type', models.CharField(max_length=50, verbose_name='Type')),
                ('status', models.CharField(db_index=True, default='NEW', max_length=50, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('assigned', models.DateTimeField(blank=True, null=True, verbose_name='Assigned')),
                ('started', models.DateTimeField(blank=True, null=True, verbose_name='Started')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Finished')),
                ('previous', models.ManyToManyField(related_name='leading', to='project.abstask', verbose_name='Previous')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=255, null=True, verbose_name='工作阶段')),
                ('output_list', models.CharField(blank=True, max_length=255, null=True, verbose_name='成果清单')),
                ('creator', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='achievement_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('absprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.absprocess')),
                ('artifact_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('artifact_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Process list',
                'ordering': ['-created'],
            },
            bases=('project.absprocess',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255, unique=True, verbose_name='合同编号')),
                ('project_title', models.CharField(max_length=255, unique_for_year='project_created', verbose_name='项目名称')),
                ('project_type', models.CharField(choices=[('0', '前瞻研究'), ('1', '策划规划设计'), ('2', '研讨竞赛'), ('3', '顾问咨询')], max_length=10, verbose_name='项目类型')),
                ('project_cate', models.CharField(choices=[('0', '创新研究'), ('1', '业务服务')], max_length=10, verbose_name='项目类型')),
                ('project_created', models.DateTimeField(auto_now_add=True, verbose_name='项目创建时间')),
                ('status', models.CharField(choices=[('NEW', '新创建'), ('START', '成果上传中'), ('END', '项目结束'), ('LOCK', '项目锁定')], db_index=True, default='NEW', max_length=10, verbose_name='项目状态')),
                ('project_approver', models.ManyToManyField(db_index=True, limit_choices_to={'role': 4}, related_name='project_approver', related_query_name='project_approval_to', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('project_issuer', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='project_issuer', related_query_name='project_issued', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project_sponsor', models.ManyToManyField(db_index=True, limit_choices_to={'role': 3}, related_name='project_sponsor', related_query_name='project_responsible_for', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project_team', models.ManyToManyField(to='auth.group', verbose_name='项目组')),
            ],
        ),
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.achievement', verbose_name='成果')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('abstask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.abstask')),
                ('artifact_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('external_task_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='External Task ID')),
                ('owner_permission', models.CharField(blank=True, max_length=255, null=True, verbose_name='Permission')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('data', models.JSONField(blank=True, null=True)),
                ('artifact_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_task_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.process', verbose_name='Process')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created'],
            },
            bases=('project.abstask',),
        ),
    ]
