# Generated by Django 4.0.3 on 2022-04-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='项目编号'),
            preserve_default=False,
        ),
    ]
