# Generated by Django 4.0.3 on 2022-05-05 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_project_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(db_index=True, limit_choices_to={'role_in': [3, 2, 1, 5]}, related_name='member', related_query_name='project_member', to=settings.AUTH_USER_MODEL, verbose_name='项目组成员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_sponsor',
            field=models.ManyToManyField(db_index=True, related_name='project_sponsor', related_query_name='project_responsible_for', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
    ]
