# Generated by Django 4.0.3 on 2022-05-05 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_alter_project_project_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='test1', max_length=25, verbose_name='成果名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_issuer', related_query_name='project_issued', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(db_index=True, limit_choices_to={'role__in': [3, 2, 1, 5]}, related_name='member', related_query_name='project_member', to=settings.AUTH_USER_MODEL, verbose_name='项目组成员'),
        ),
    ]
