# Generated by Django 4.0.3 on 2022-05-05 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0010_achievement_name_alter_project_project_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanager',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome_owner', to=settings.AUTH_USER_MODEL, verbose_name='文件上传人'),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='file',
            field=models.FileField(null=True, upload_to='project/achievement/outcome/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='filemanager',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.achievement', verbose_name='成果文件'),
        ),
    ]
