# Generated by Django 4.0.3 on 2022-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_filemanager_created_filemanager_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanager',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件名'),
        ),
    ]
