# Generated by Django 4.0.3 on 2022-05-07 02:09

from django.db import migrations, models
import ums.apps.project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_taggedfile_alter_filemanager_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='file',
            field=models.FileField(null=True, upload_to=ums.apps.project.models.achievement_file_name),
        ),
    ]
