# Generated by Django 4.0.3 on 2022-05-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_filemanager_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-created', '-updated'], 'permissions': [('submit_achievement', 'Can submit achievement'), ('withdraw_achievement', 'Can withdraw achievement'), ('approve_achievement_lv1', 'Can approve achievement lv1'), ('approve_achievement_lv2', 'Can approve achievement lv2'), ('final_review_achievement', 'Can final review achievement')]},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-project_created']},
        ),
    ]
