# Generated by Django 4.0.3 on 2022-06-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_alter_achievement_state_alter_achievement_status1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['-finished', '-id', '-created'], 'verbose_name': 'Process', 'verbose_name_plural': 'Process list'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id', 'finished'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='achievement',
            name='contract_type',
            field=models.CharField(choices=[('0', '主合同'), ('1', '外协合同')], db_index=True, default='0', max_length=5, verbose_name='合同类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', related_query_name='tasks', to='project.process', verbose_name='Process'),
        ),
    ]
